# generated by appcreator
from django.contrib import admin
from .models import (
    ArtWork,
    Book,
    Institution,
    Person,
    Text,
)

admin.site.register(ArtWork)
admin.site.register(Book)
admin.site.register(Institution)
admin.site.register(Person)
admin.site.register(Text)
