# generated by appcreator
from django.db.models import Q
from dal import autocomplete
from . models import (
    ArtWork,
    Book,
    Institution,
    Person,
    Text,
)


class ArtWorkAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = ArtWork.objects.all()

        if self.q:
            qs = qs.filter(
                Q(legacy_id__icontains=self.q) |
                Q(name__icontains=self.q)
            )
        return qs


class BookAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Book.objects.all()

        if self.q:
            qs = qs.filter(
                Q(legacy_id__icontains=self.q) |
                Q(legacy_pk__icontains=self.q)
            )
        return qs


class InstitutionAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Institution.objects.all()

        if self.q:
            qs = qs.filter(
                Q(legacy_id__icontains=self.q) |
                Q(name__icontains=self.q)
            )
        return qs


class PersonAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Person.objects.all()

        if self.q:
            qs = qs.filter(
                Q(legacy_id__icontains=self.q) |
                Q(legacy_pk__icontains=self.q)
            )
        return qs


class TextAC(autocomplete.Select2QuerySetView):
    def get_queryset(self):
        qs = Text.objects.all()

        if self.q:
            qs = qs.filter(
                Q(legacy_id__icontains=self.q) |
                Q(legacy_pk__icontains=self.q)
            )
        return qs


