# generated by appcreator
import django_tables2 as tables

from browsing.browsing_utils import MergeColumn
from . models import (
    ArtWork,
    Book,
    Institution,
    Person,
    Text,
)


class ArtWorkTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = ArtWork
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class BookTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Book
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class InstitutionTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Institution
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class PersonTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Person
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}


class TextTable(tables.Table):

    id = tables.LinkColumn(verbose_name='ID')
    merge = MergeColumn(verbose_name='keep | remove', accessor='pk')

    class Meta:
        model = Text
        sequence = ('id',)
        attrs = {"class": "table table-responsive table-hover"}

