# generated by appcreator
from django.urls import path
from . import views

app_name = "archiv"
urlpatterns = [
    path("artwork/", views.ArtWorkListView.as_view(), name="artwork_browse"),
    path(
        "artwork/detail/<int:pk>",
        views.ArtWorkDetailView.as_view(),
        name="artwork_detail",
    ),
    path("artwork/create/", views.ArtWorkCreate.as_view(), name="artwork_create"),
    path("artwork/edit/<int:pk>", views.ArtWorkUpdate.as_view(), name="artwork_edit"),
    path(
        "artwork/delete/<int:pk>", views.ArtWorkDelete.as_view(), name="artwork_delete"
    ),
    path("book/", views.BookListView.as_view(), name="book_browse"),
    path("book/detail/<int:pk>", views.BookDetailView.as_view(), name="book_detail"),
    path("book/create/", views.BookCreate.as_view(), name="book_create"),
    path("book/edit/<int:pk>", views.BookUpdate.as_view(), name="book_edit"),
    path("book/delete/<int:pk>", views.BookDelete.as_view(), name="book_delete"),
    path(
        "institution/", views.InstitutionListView.as_view(), name="institution_browse"
    ),
    path(
        "institution/detail/<int:pk>",
        views.InstitutionDetailView.as_view(),
        name="institution_detail",
    ),
    path(
        "institution/create/",
        views.InstitutionCreate.as_view(),
        name="institution_create",
    ),
    path(
        "institution/edit/<int:pk>",
        views.InstitutionUpdate.as_view(),
        name="institution_edit",
    ),
    path(
        "institution/delete/<int:pk>",
        views.InstitutionDelete.as_view(),
        name="institution_delete",
    ),
    path("person/", views.PersonListView.as_view(), name="person_browse"),
    path(
        "person/detail/<int:pk>", views.PersonDetailView.as_view(), name="person_detail"
    ),
    path("person/create/", views.PersonCreate.as_view(), name="person_create"),
    path("person/edit/<int:pk>", views.PersonUpdate.as_view(), name="person_edit"),
    path("person/delete/<int:pk>", views.PersonDelete.as_view(), name="person_delete"),
    path("text/", views.TextListView.as_view(), name="text_browse"),
    path("text/detail/<int:pk>", views.TextDetailView.as_view(), name="text_detail"),
    path("text/create/", views.TextCreate.as_view(), name="text_create"),
    path("text/edit/<int:pk>", views.TextUpdate.as_view(), name="text_edit"),
    path("text/delete/<int:pk>", views.TextDelete.as_view(), name="text_delete"),
]
