# Generated by Django 5.1.1 on 2024-09-27 15:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Titel des Buches",
                        max_length=250,
                        verbose_name="Titel",
                    ),
                ),
                (
                    "written_date",
                    models.CharField(
                        blank=True,
                        help_text="Jahr",
                        max_length=250,
                        verbose_name="Jahr",
                    ),
                ),
                (
                    "alt_written_date",
                    models.CharField(
                        blank=True,
                        help_text="Jahr (2)",
                        max_length=250,
                        verbose_name="Jahr (2)",
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
            ],
            options={
                "verbose_name": "Book",
                "ordering": ["legacy_pk"],
            },
        ),
        migrations.CreateModel(
            name="Institution",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Name",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
            ],
            options={
                "verbose_name": "Institution",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Person",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Titel des Kunstwerkes",
                        max_length=250,
                        verbose_name="Name",
                    ),
                ),
                (
                    "alt_name",
                    models.CharField(
                        blank=True,
                        help_text="Alternative Bezeichnung",
                        max_length=250,
                        verbose_name="Alternative Bezeichnung",
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
            ],
            options={
                "verbose_name": "Person",
                "ordering": ["legacy_pk"],
            },
        ),
        migrations.CreateModel(
            name="ArtWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True,
                        help_text="Titel des Kunstwerkes",
                        max_length=250,
                        verbose_name="Titel",
                    ),
                ),
                (
                    "alt_name",
                    models.CharField(
                        blank=True,
                        help_text="Alternative Bezeichnung",
                        max_length=250,
                        verbose_name="Alternative Bezeichnung",
                    ),
                ),
                (
                    "written_date",
                    models.CharField(
                        blank=True,
                        help_text="Datierung",
                        max_length=250,
                        verbose_name="Datierung",
                    ),
                ),
                (
                    "material",
                    models.CharField(
                        blank=True,
                        help_text="Material",
                        max_length=250,
                        verbose_name="Material",
                    ),
                ),
                (
                    "dimensions",
                    models.CharField(
                        blank=True,
                        help_text="Dimensionen",
                        max_length=250,
                        verbose_name="Dimensionen",
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
                (
                    "part_of",
                    models.ForeignKey(
                        blank=True,
                        help_text="Teil von",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_artwork_part_of_artwork",
                        to="archiv.artwork",
                        verbose_name="Teil von",
                    ),
                ),
                (
                    "holding_institution",
                    models.ForeignKey(
                        blank=True,
                        help_text="in Museum/Sammlung",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_artwork_holding_institution_institution",
                        to="archiv.institution",
                        verbose_name="in Museum",
                    ),
                ),
            ],
            options={
                "verbose_name": "Kunstwerk",
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="Text",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "legacy_id",
                    models.CharField(
                        blank=True, max_length=300, verbose_name="Legacy ID"
                    ),
                ),
                (
                    "legacy_pk",
                    models.IntegerField(
                        blank=True,
                        help_text="Primärschlüssel Alt",
                        null=True,
                        verbose_name="Primärschlüssel Alt",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True, help_text="Text", null=True, verbose_name="Text"
                    ),
                ),
                (
                    "source",
                    models.TextField(
                        blank=True, help_text="Quelle", null=True, verbose_name="Quelle"
                    ),
                ),
                (
                    "orig_data_csv",
                    models.TextField(
                        blank=True, null=True, verbose_name="The original data"
                    ),
                ),
                (
                    "book",
                    models.ForeignKey(
                        blank=True,
                        help_text="Buch",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="rvn_text_book_book",
                        to="archiv.book",
                        verbose_name="Buch",
                    ),
                ),
            ],
            options={
                "verbose_name": "Text",
                "ordering": ["legacy_pk"],
            },
        ),
    ]
