# Generated by Django 5.1.1 on 2024-09-28 06:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="person",
            name="author_of",
            field=models.ManyToManyField(
                blank=True,
                help_text="Autorin/Autor von",
                related_name="has_author",
                to="archiv.book",
                verbose_name="Autorin/Autor von",
            ),
        ),
        migrations.AddField(
            model_name="person",
            name="painter_of",
            field=models.ManyToManyField(
                blank=True,
                help_text="Malerin/Maler von",
                related_name="has_painter",
                to="archiv.book",
                verbose_name="Malerin/Maler von",
            ),
        ),
        migrations.AddField(
            model_name="text",
            name="mentioned_artwork",
            field=models.ManyToManyField(
                blank=True,
                help_text="im Text erwähnte Kunstwerke",
                related_name="artwork_mentioned_in",
                to="archiv.artwork",
                verbose_name="erwähnte Kunstwerke",
            ),
        ),
        migrations.AddField(
            model_name="text",
            name="mentioned_person",
            field=models.ManyToManyField(
                blank=True,
                help_text="im Text erwähnte Personen",
                related_name="person_mentioned_in",
                to="archiv.person",
                verbose_name="erwähnte Personen",
            ),
        ),
    ]
