# Generated by Django 5.1.1 on 2024-09-28 07:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("archiv", "0002_person_author_of_person_painter_of_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="text",
            options={"ordering": ["id"], "verbose_name": "Text"},
        ),
    ]
