# Generated by Django 5.1.1 on 2024-09-28 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("archiv", "0003_alter_text_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="person",
            name="painter_of",
            field=models.ManyToManyField(
                blank=True,
                help_text="Malerin/Maler von",
                related_name="has_painter",
                to="archiv.artwork",
                verbose_name="Malerin/Maler von",
            ),
        ),
    ]
